// <auto-generated />
using System;
using IndividualsDirectory.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndividualsDirectory.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427143201_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndividualsDirectory.Data.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tbilisi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Batumi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kutaisi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rustavi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gori"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Zugdidi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Poti"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Telavi"
                        });
                });

            modelBuilder.Entity("IndividualsDirectory.Data.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IndividualId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IndividualId = 1,
                            Number = "+995555111001",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            IndividualId = 1,
                            Number = "+995322111002",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            IndividualId = 2,
                            Number = "+995555222001",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            IndividualId = 3,
                            Number = "+995555333001",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            IndividualId = 4,
                            Number = "+995431444001",
                            Type = 3
                        },
                        new
                        {
                            Id = 6,
                            IndividualId = 5,
                            Number = "+995555555001",
                            Type = 1
                        });
                });

            modelBuilder.Entity("IndividualsDirectory.Data.Entities.Individual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.HasIndex("PersonalNumber")
                        .IsUnique();

                    b.ToTable("Individuals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            DateOfBirth = new DateOnly(1990, 5, 15),
                            FirstName = "Giorgi",
                            Gender = 2,
                            LastName = "Beridze",
                            PersonalNumber = "01001011001"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            DateOfBirth = new DateOnly(1992, 8, 20),
                            FirstName = "Nino",
                            Gender = 1,
                            LastName = "Kapanadze",
                            PersonalNumber = "01001011002"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            DateOfBirth = new DateOnly(1985, 3, 10),
                            FirstName = "Davit",
                            Gender = 2,
                            LastName = "Tsiklauri",
                            PersonalNumber = "01001011003"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            DateOfBirth = new DateOnly(1995, 12, 5),
                            FirstName = "Mariam",
                            Gender = 1,
                            LastName = "Lomidze",
                            PersonalNumber = "01001011004"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 4,
                            DateOfBirth = new DateOnly(1988, 7, 25),
                            FirstName = "Levan",
                            Gender = 2,
                            LastName = "Adamia",
                            PersonalNumber = "01001011005"
                        });
                });

            modelBuilder.Entity("IndividualsDirectory.Data.Entities.IndividualConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectedIndividualId")
                        .HasColumnType("int");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("int");

                    b.Property<int>("IndividualId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedIndividualId");

                    b.HasIndex("IndividualId", "ConnectedIndividualId")
                        .IsUnique();

                    b.ToTable("IndividualConnections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectedIndividualId = 2,
                            ConnectionType = 1,
                            IndividualId = 1
                        },
                        new
                        {
                            Id = 2,
                            ConnectedIndividualId = 1,
                            ConnectionType = 1,
                            IndividualId = 2
                        },
                        new
                        {
                            Id = 3,
                            ConnectedIndividualId = 3,
                            ConnectionType = 3,
                            IndividualId = 1
                        },
                        new
                        {
                            Id = 4,
                            ConnectedIndividualId = 1,
                            ConnectionType = 3,
                            IndividualId = 3
                        },
                        new
                        {
                            Id = 5,
                            ConnectedIndividualId = 4,
                            ConnectionType = 2,
                            IndividualId = 2
                        },
                        new
                        {
                            Id = 6,
                            ConnectedIndividualId = 2,
                            ConnectionType = 2,
                            IndividualId = 4
                        },
                        new
                        {
                            Id = 7,
                            ConnectedIndividualId = 5,
                            ConnectionType = 4,
                            IndividualId = 3
                        },
                        new
                        {
                            Id = 8,
                            ConnectedIndividualId = 3,
                            ConnectionType = 4,
                            IndividualId = 5
                        });
                });

            modelBuilder.Entity("IndividualsDirectory.Data.Entities.Contact", b =>
                {
                    b.HasOne("IndividualsDirectory.Data.Entities.Individual", "Individual")
                        .WithMany("Contacts")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("IndividualsDirectory.Data.Entities.Individual", b =>
                {
                    b.HasOne("IndividualsDirectory.Data.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("IndividualsDirectory.Data.Entities.IndividualConnection", b =>
                {
                    b.HasOne("IndividualsDirectory.Data.Entities.Individual", "ConnectedIndividual")
                        .WithMany()
                        .HasForeignKey("ConnectedIndividualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndividualsDirectory.Data.Entities.Individual", "Individual")
                        .WithMany("Connections")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedIndividual");

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("IndividualsDirectory.Data.Entities.Individual", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
